//
// 00h 0x00
// 01h Other
// 02h Unknown
// 03h 8086
// 04h 80286
// 05h Intel386™ processor
// 06h Intel486™ processor
// 07h 8087
// 08h 80287
// 09h 80387
// 0Ah 80487
// 0Bh Pentium® processor Family
// 0Ch Pentium® Pro processor
// 0Dh Pentium® II processor
// 0Eh Pentium® processor with MMX™ technology
// 0Fh Celeron™ processor
// 10h Pentium® II Xeon™ processor
// 11h Pentium® III processor
// 12h M1 Family
// 13h M2 Family
// 14h 0x14
// 15h 0x15
// 16h 0x16
// 17h 0x17
// 18h AMD Duron™ Processor Family
// 19h K5 Family
// 1Ah K6 Family
// 1Bh K6-2
// 1Ch K6-3
// 1Dh AMD Athlon™ Processor Family
// 1Eh AMD2900 Family
// 1Fh K6-2+
// 20h Power PC Family
// 21h Power PC 601
// 22h Power PC 603
// 23h Power PC 603+
// 24h Power PC 604
// 25h Power PC 620
// 26h Power PC x704
// 27h Power PC 750
// 28h 0x28
// 29h 0x29
// 2Ah 0x2A
// 2Bh 0x2B
// 2Ch 0x2C
// 2Dh 0x2D
// 2Eh 0x2E
// 2Fh 0x2F
// 30h Alpha Family3
// 31h Alpha 21064
// 32h Alpha 21066
// 33h Alpha 21164
// 34h Alpha 21164PC
// 35h Alpha 21164a
// 36h Alpha 21264
// 37h Alpha 21364
// 38h 0x38
// 39h 0x39
// 3Ah 0x3A
// 3Bh 0x3B
// 3Ch 0x3C
// 3Dh 0x3D
// 3Eh 0x3E
// 3Fh 0x3F
// 40h MIPS Family
// 41h MIPS R4000
// 42h MIPS R4200
// 43h MIPS R4400
// 44h MIPS R4600
// 45h MIPS R10000
// 46h 0x46
// 47h 0x47
// 48h 0x48
// 49h 0x49
// 4Ah 0x4A
// 4Bh 0x4B
// 4Ch 0x4C
// 4Dh 0x4D
// 4Eh 0x4E
// 4Fh 0x4F
// 50h SPARC Family
// 51h SuperSPARC
// 52h microSPARC II
// 53h microSPARC IIep
// 54h UltraSPARC
// 55h UltraSPARC II
// 56h UltraSPARC IIi
// 57h UltraSPARC III
// 58h UltraSPARC IIIi
// 59h 0x59
// 5Ah 0x5A
// 5Bh 0x5B
// 5Ch 0x5C
// 5Dh 0x5D
// 5Eh 0x5E
// 5Fh 0x5F
// 60h 68040 Family
// 61h 68xxx
// 62h 68000
// 63h 68010
// 64h 68020
// 65h 68030
// 66h 0x66
// 67h 0x67
// 68h 0x68
// 69h 0x69
// 6Ah 0x6A
// 6Bh 0x6B
// 6Ch 0x6C
// 6Dh 0x6D
// 6Eh 0x6E
// 6Fh 0x6F
// 70h Hobbit Family
// 71h 0x71
// 72h 0x72
// 73h 0x73
// 74h 0x74
// 75h 0x75
// 76h 0x76
// 77h 0x77
// 78h Crusoe™ TM5000 Family
// 79h Crusoe™ TM3000 Family
// 7Ah Efficeon™ TM8000 Family
// 7Bh 0x7B
// 7Ch 0x7C
// 7Dh 0x7D
// 7Eh 0x7E
// 7Fh 0x7F
// 80h Weitek
// 81h 0x81
// 82h Itanium™ processor
// 83h AMD Athlon™ 64 Processor Family
// 84h AMD Opteron™ Processor Family
// 85h 0x85
// 86h 0x86
// 87h 0x87
// 88h 0x88
// 89h 0x89
// 8Ah 0x8A
// 8Bh 0x8B
// 8Ch 0x8C
// 8Dh 0x8D
// 8Eh 0x8E
// 8Fh 0x8F
// 90h PA-RISC Family
// 91h PA-RISC 8500
// 92h PA-RISC 8000
// 93h PA-RISC 7300LC
// 94h PA-RISC 7200
// 95h PA-RISC 7100LC
// 96h PA-RISC 7100
// 97h 0x97
// 98h 0x98
// 99h 0x99
// 9Ah 0x9A
// 9Bh 0x9B
// 9Ch 0x9C
// 9Dh 0x9D
// 9Eh 0x9E
// 9Fh 0x9F
// A0h V30 Family
// A1h 0xA1
// A2h 0xA2
// A3h 0xA3
// A4h 0xA4
// A5h 0xA5
// A6h 0xA6
// A7h 0xA7
// A8h 0xA8
// A9h 0xA9
// AAh 0xAA
// ABh 0xAB
// ACh 0xAC
// ADh 0xAD
// AEh 0xAE
// AFh 0xAF
// B0h Pentium® III Xeon™ processor
// B1h Pentium® III Processor with Intel® SpeedStep™ Technology
// B2h Pentium® 4 Processor
// B3h Intel® Xeon™
// B4h AS400 Family
// B5h Intel® Xeon™ processor MP
// B6h AMD Athlon™ XP Processor Family
// B7h AMD Athlon™ MP Processor Family
// B8h Intel® Itanium® 2 processor
// B9h Intel® Pentium® M processor
// BAh 0xBA
// BBh 0xBB
// BCh 0xBC
// BDh 0xBD
// BEh 0xBE
// BFh 0xBF
// C0h 0xC0
// C1h 0xC1
// C2h 0xC2
// C3h 0xC3
// C4h 0xC4
// C5h 0xC5
// C6h 0xC6
// C7h 0xC7
// C8h IBM390 Family
// C9h G4
// CAh G5
// CBh 0xCB
// CCh 0xCC
// CDh 0xCD
// CEh 0xCE
// CFh 0xCF
// D0h 0xD0
// D1h 0xD1
// D2h 0xD2
// D3h 0xD3
// D4h 0xD4
// D5h 0xD5
// D6h 0xD6
// D7h 0xD7
// D8h 0xD8
// D9h 0xD9
// DAh 0xDA
// DBh 0xDB
// DCh 0xDC
// DDh 0xDD
// DEh 0xDE
// DFh 0xDF
// E0h 0xE0
// E1h 0xE1
// E2h 0xE2
// E3h 0xE3
// E4h 0xE4
// E5h 0xE5
// E6h 0xE6
// E7h 0xE7
// E8h 0xE8
// E9h 0xE9
// EAh 0xEA
// EBh 0xEB
// ECh 0xEC
// EDh 0xED
// EEh 0xEE
// EFh 0xEF
// F0h 0xF0
// F1h 0xF1
// F2h 0xF2
// F3h 0xF3
// F4h 0xF4
// F5h 0xF5
// F6h 0xF6
// F7h 0xF7
// F8h 0xF8
// F9h 0xF9
// FAh i860
// FBh i960
// FCh 0xFC
// FDh 0xFD
// FEh 0xFE
// FFh 0xFF

