{
00h Unnasigned_00
01h Other
02h Unknown
03h 8086
04h 80286
05h Intel386(TM) processor
06h Intel486(TM) processor
07h 8087
08h 80287
09h 80387
0Ah 80487
0Bh Pentium(R) processor Family
0Ch Pentium(R) Pro processor
0Dh Pentium(R) II processor
0Eh Pentium(R) processor with MMX(TM) technology
0Fh Celeron(TM) processor
10h Pentium(R) II Xeon(TM) processor
11h Pentium(R) III processor
12h M1 Family
13h M2 Family
14h Unnasigned_14
15h Unnasigned_15
16h Unnasigned_16
17h Unnasigned_17
18h AMD Duron(TM) Processor Family
19h K5 Family
1Ah K6 Family
1Bh K6-2
1Ch K6-3
1Dh AMD Athlon(TM) Processor Family
1Eh AMD2900 Family
1Fh K6-2+
20h Power PC Family
21h Power PC 601
22h Power PC 603
23h Power PC 603+
24h Power PC 604
25h Power PC 620
26h Power PC x704
27h Power PC 750
28h Unnasigned_28
29h Unnasigned_29
2Ah Unnasigned_2A
2Bh Unnasigned_2B
2Ch Unnasigned_2C
2Dh Unnasigned_2D
2Eh Unnasigned_2E
2Fh Unnasigned_2F
30h Alpha Family3
31h Alpha 21064
32h Alpha 21066
33h Alpha 21164
34h Alpha 21164PC
35h Alpha 21164a
36h Alpha 21264
37h Alpha 21364
38h Unnasigned_38
39h Unnasigned_39
3Ah Unnasigned_3A
3Bh Unnasigned_3B
3Ch Unnasigned_3C
3Dh Unnasigned_3D
3Eh Unnasigned_3E
3Fh Unnasigned_3F
40h MIPS Family
41h MIPS R4000
42h MIPS R4200
43h MIPS R4400
44h MIPS R4600
45h MIPS R10000
46h Unnasigned_46
47h Unnasigned_47
48h Unnasigned_48
49h Unnasigned_49
4Ah Unnasigned_4A
4Bh Unnasigned_4B
4Ch Unnasigned_4C
4Dh Unnasigned_4D
4Eh Unnasigned_4E
4Fh Unnasigned_4F
50h SPARC Family
51h SuperSPARC
52h microSPARC II
53h microSPARC IIep
54h UltraSPARC
55h UltraSPARC II
56h UltraSPARC IIi
57h UltraSPARC III
58h UltraSPARC IIIi
59h Unnasigned_59
5Ah Unnasigned_5A
5Bh Unnasigned_5B
5Ch Unnasigned_5C
5Dh Unnasigned_5D
5Eh Unnasigned_5E
5Fh Unnasigned_5F
60h 68040 Family
61h 68xxx
62h 68000
63h 68010
64h 68020
65h 68030
66h Unnasigned_66
67h Unnasigned_67
68h Unnasigned_68
69h Unnasigned_69
6Ah Unnasigned_6A
6Bh Unnasigned_6B
6Ch Unnasigned_6C
6Dh Unnasigned_6D
6Eh Unnasigned_6E
6Fh Unnasigned_6F
70h Hobbit Family
71h Unnasigned_71
72h Unnasigned_72
73h Unnasigned_73
74h Unnasigned_74
75h Unnasigned_75
76h Unnasigned_76
77h Unnasigned_77
78h Crusoe(TM) TM5000 Family
79h Crusoe(TM) TM3000 Family
7Ah Efficeon(TM) TM8000 Family
7Bh Unnasigned_7B
7Ch Unnasigned_7C
7Dh Unnasigned_7D
7Eh Unnasigned_7E
7Fh Unnasigned_7F
80h Weitek
81h Unnasigned_81
82h Itanium(TM) processor
83h AMD Athlon(TM) 64 Processor Family
84h AMD Opteron(TM) Processor Family
85h Unnasigned_85
86h Unnasigned_86
87h Unnasigned_87
88h Unnasigned_88
89h Unnasigned_89
8Ah Unnasigned_8A
8Bh Unnasigned_8B
8Ch Unnasigned_8C
8Dh Unnasigned_8D
8Eh Unnasigned_8E
8Fh Unnasigned_8F
90h PA-RISC Family
91h PA-RISC 8500
92h PA-RISC 8000
93h PA-RISC 7300LC
94h PA-RISC 7200
95h PA-RISC 7100LC
96h PA-RISC 7100
97h Unnasigned_97
98h Unnasigned_98
99h Unnasigned_99
9Ah Unnasigned_9A
9Bh Unnasigned_9B
9Ch Unnasigned_9C
9Dh Unnasigned_9D
9Eh Unnasigned_9E
9Fh Unnasigned_9F
A0h V30 Family
A1h Unnasigned_A1
A2h Unnasigned_A2
A3h Unnasigned_A3
A4h Unnasigned_A4
A5h Unnasigned_A5
A6h Unnasigned_A6
A7h Unnasigned_A7
A8h Unnasigned_A8
A9h Unnasigned_A9
AAh Unnasigned_AA
ABh Unnasigned_AB
ACh Unnasigned_AC
ADh Unnasigned_AD
AEh Unnasigned_AE
AFh Unnasigned_AF
B0h Pentium(R) III Xeon(TM) processor
B1h Pentium(R) III Processor with Intel(R) SpeedStep(TM) Technology
B2h Pentium(R) 4 Processor
B3h Intel(R) Xeon(TM)
B4h AS400 Family
B5h Intel(R) Xeon(TM) processor MP
B6h AMD Athlon(TM) XP Processor Family
B7h AMD Athlon(TM) MP Processor Family
B8h Intel(R) Itanium(R) 2 processor
B9h Intel(R) Pentium(R) M processor
BAh Unnasigned_BA
BBh Unnasigned_BB
BCh Unnasigned_BC
BDh Unnasigned_BD
BEh Unnasigned_BE
BFh Unnasigned_BF
C0h Unnasigned_C0
C1h Unnasigned_C1
C2h Unnasigned_C2
C3h Unnasigned_C3
C4h Unnasigned_C4
C5h Unnasigned_C5
C6h Unnasigned_C6
C7h Unnasigned_C7
C8h IBM390 Family
C9h G4
CAh G5
CBh Unnasigned_CB
CCh Unnasigned_CC
CDh Unnasigned_CD
CEh Unnasigned_CE
CFh Unnasigned_CF
D0h Unnasigned_D0
D1h Unnasigned_D1
D2h Unnasigned_D2
D3h Unnasigned_D3
D4h Unnasigned_D4
D5h Unnasigned_D5
D6h Unnasigned_D6
D7h Unnasigned_D7
D8h Unnasigned_D8
D9h Unnasigned_D9
DAh Unnasigned_DA
DBh Unnasigned_DB
DCh Unnasigned_DC
DDh Unnasigned_DD
DEh Unnasigned_DE
DFh Unnasigned_DF
E0h Unnasigned_E0
E1h Unnasigned_E1
E2h Unnasigned_E2
E3h Unnasigned_E3
E4h Unnasigned_E4
E5h Unnasigned_E5
E6h Unnasigned_E6
E7h Unnasigned_E7
E8h Unnasigned_E8
E9h Unnasigned_E9
EAh Unnasigned_EA
EBh Unnasigned_EB
ECh Unnasigned_EC
EDh Unnasigned_ED
EEh Unnasigned_EE
EFh Unnasigned_EF
F0h Unnasigned_F0
F1h Unnasigned_F1
F2h Unnasigned_F2
F3h Unnasigned_F3
F4h Unnasigned_F4
F5h Unnasigned_F5
F6h Unnasigned_F6
F7h Unnasigned_F7
F8h Unnasigned_F8
F9h Unnasigned_F9
FAh i860
FBh i960
FCh Unnasigned_FC
FDh Unnasigned_FD
FEh Unnasigned_FE
FFh Unnasigned_FF
}

TProcessorFamily = (
  pfNone,
  pfOther,
  pfUnknown,
  pf8086,
  pf80286,
  pfIntel386,
  pfIntel486,
  pf8087,
  pf80287,
  pf80387,
  pf80487,
  pfPentium_Family,
  pfPentiumPro,
  pfPentiumII,
  pfPentiumMMX,
  pfCeleron,
  pfPentiumIIXeon,
  pfPentiumIII,
  pfM1_Family,
  pfM2_Family,
  pfUnnasigned_14,
  pfUnnasigned_15,
  pfUnnasigned_16,
  pfUnnasigned_17,
  pfAMDDuron_Family,
  pfK5_Family,
  pfK6_Family,
  pfK62,
  pfK63,
  pfAMDAthlon_Family,
  pfAMD2900_Family,
  pfK62P,
  pfPowerPC_Family,
  pfPowerPC601,
  pfPowerPC603,
  pfPowerPC603P,
  pfPowerPC604,
  pfPowerPC620,
  pfPowerPCx704,
  pfPowerPC750,
  pfUnnasigned_28,
  pfUnnasigned_29,
  pfUnnasigned_2A,
  pfUnnasigned_2B,
  pfUnnasigned_2C,
  pfUnnasigned_2D,
  pfUnnasigned_2E,
  pfUnnasigned_2F,
  pfAlpha_Family,
  pfAlpha21064,
  pfAlpha21066,
  pfAlpha21164,
  pfAlpha21164PC,
  pfAlpha21164A,
  pfAlpha21264,
  pfAlpha21364,
  pfUnnasigned_38,
  pfUnnasigned_39,
  pfUnnasigned_3A,
  pfUnnasigned_3B,
  pfUnnasigned_3C,
  pfUnnasigned_3D,
  pfUnnasigned_3E,
  pfUnnasigned_3F,
  pfMIPS_Family,
  pfMIPSR4000,
  pfMIPSR4200,
  pfMIPSR4400,
  pfMIPSR4600,
  pfMIPSR10000,
  pfUnnasigned_46,
  pfUnnasigned_47,
  pfUnnasigned_48,
  pfUnnasigned_49,
  pfUnnasigned_4A,
  pfUnnasigned_4B,
  pfUnnasigned_4C,
  pfUnnasigned_4D,
  pfUnnasigned_4E,
  pfUnnasigned_4F,
  pfSPARC_Family,
  pfSuperSPARC,
  pfmicroSPARC2,
  pfmicroSPARC2ep,
  pfUltraSPARC,
  pfUltraSPARC2,
  pfUltraSPARC2i,
  pfUltraSPARC3,
  pfUltraSPARC3i,
  pfUnnasigned_59,
  pfUnnasigned_5A,
  pfUnnasigned_5B,
  pfUnnasigned_5C,
  pfUnnasigned_5D,
  pfUnnasigned_5E,
  pfUnnasigned_5F,
  pf68040_Family,
  pf68xxx,
  pf68000,
  pf68010,
  pf68020,
  pf68030,
  pfUnnasigned_66,
  pfUnnasigned_67,
  pfUnnasigned_68,
  pfUnnasigned_69,
  pfUnnasigned_6A,
  pfUnnasigned_6B,
  pfUnnasigned_6C,
  pfUnnasigned_6D,
  pfUnnasigned_6E,
  pfUnnasigned_6F,
  pfHobbit_Family,
  pfUnnasigned_71,
  pfUnnasigned_72,
  pfUnnasigned_73,
  pfUnnasigned_74,
  pfUnnasigned_75,
  pfUnnasigned_76,
  pfUnnasigned_77,
  pfCrusoeTM5000_Family,
  pfCrusoeTM3000_Family,
  pfEfficeonTM8000_Family,
  pfUnnasigned_7B,
  pfUnnasigned_7C,
  pfUnnasigned_7D,
  pfUnnasigned_7E,
  pfUnnasigned_7F,
  pfWeitek,
  pfUnnasigned_81,
  pfItanium,
  pfAMDAthlon64_Family,
  pfAMDOpteron_Family,
  pfUnnasigned_85,
  pfUnnasigned_86,
  pfUnnasigned_87,
  pfUnnasigned_88,
  pfUnnasigned_89,
  pfUnnasigned_8A,
  pfUnnasigned_8B,
  pfUnnasigned_8C,
  pfUnnasigned_8D,
  pfUnnasigned_8E,
  pfUnnasigned_8F,
  pfPA - RISC_Family,
  pfPA - RISC8500,
  pfPA - RISC8000,
  pfPA - RISC7300LC,
  pfPA - RISC7200,
  pfPA - RISC7100LC,
  pfPA - RISC7100,
  pfUnnasigned_97,
  pfUnnasigned_98,
  pfUnnasigned_99,
  pfUnnasigned_9A,
  pfUnnasigned_9B,
  pfUnnasigned_9C,
  pfUnnasigned_9D,
  pfUnnasigned_9E,
  pfUnnasigned_9F,
  pfV30_Family,
  pfUnnasigned_A1,
  pfUnnasigned_A2,
  pfUnnasigned_A3,
  pfUnnasigned_A4,
  pfUnnasigned_A5,
  pfUnnasigned_A6,
  pfUnnasigned_A7,
  pfUnnasigned_A8,
  pfUnnasigned_A9,
  pfUnnasigned_AA,
  pfUnnasigned_AB,
  pfUnnasigned_AC,
  pfUnnasigned_AD,
  pfUnnasigned_AE,
  pfUnnasigned_AF,
  pfPentiumIIIXeon,
  pfPentiumIIISpeedStep,
  pfPentium4,
  pfIntelXeon,
  pfAS400_Family,
  pfIntelXeonMP,
  pfAMDAthlonXP_Family,
  pfAMDAthlonMP_Family,
  pfIntelItanium2,
  pfIntelPentiumM,
  pfUnnasigned_BA,
  pfUnnasigned_BB,
  pfUnnasigned_BC,
  pfUnnasigned_BD,
  pfUnnasigned_BE,
  pfUnnasigned_BF,
  pfUnnasigned_C0,
  pfUnnasigned_C1,
  pfUnnasigned_C2,
  pfUnnasigned_C3,
  pfUnnasigned_C4,
  pfUnnasigned_C5,
  pfUnnasigned_C6,
  pfUnnasigned_C7,
  pfIBM390_Family,
  pfG4,
  pfG5,
  pfUnnasigned_CB,
  pfUnnasigned_CC,
  pfUnnasigned_CD,
  pfUnnasigned_CE,
  pfUnnasigned_CF,
  pfUnnasigned_D0,
  pfUnnasigned_D1,
  pfUnnasigned_D2,
  pfUnnasigned_D3,
  pfUnnasigned_D4,
  pfUnnasigned_D5,
  pfUnnasigned_D6,
  pfUnnasigned_D7,
  pfUnnasigned_D8,
  pfUnnasigned_D9,
  pfUnnasigned_DA,
  pfUnnasigned_DB,
  pfUnnasigned_DC,
  pfUnnasigned_DD,
  pfUnnasigned_DE,
  pfUnnasigned_DF,
  pfUnnasigned_E0,
  pfUnnasigned_E1,
  pfUnnasigned_E2,
  pfUnnasigned_E3,
  pfUnnasigned_E4,
  pfUnnasigned_E5,
  pfUnnasigned_E6,
  pfUnnasigned_E7,
  pfUnnasigned_E8,
  pfUnnasigned_E9,
  pfUnnasigned_EA,
  pfUnnasigned_EB,
  pfUnnasigned_EC,
  pfUnnasigned_ED,
  pfUnnasigned_EE,
  pfUnnasigned_EF,
  pfUnnasigned_F0,
  pfUnnasigned_F1,
  pfUnnasigned_F2,
  pfUnnasigned_F3,
  pfUnnasigned_F4,
  pfUnnasigned_F5,
  pfUnnasigned_F6,
  pfUnnasigned_F7,
  pfUnnasigned_F8,
  pfUnnasigned_F9,
  pfi860,
  pfi960,
  pfUnnasigned_FC,
  pfUnnasigned_FD,
  pfUnnasigned_FE,
  pfUnnasigned_FF
  );

const Processors = array[TProcessorFamily] of string = (
None
Other
Unknown
8086
80286
Intel386(TM) processor
Intel486(TM) processor
8087
80287
80387
80487
Pentium(R) processor Family
Pentium(R) Pro processor
Pentium(R) II processor
Pentium(R) processor with MMX(TM) technology
Celeron(TM) processor
Pentium(R) II Xeon(TM) processor
Pentium(R) III processor
M1 Family
M2 Family
Unnasigned_14
Unnasigned_15
Unnasigned_16
Unnasigned_17
AMD Duron(TM) Processor Family
K5 Family
K6 Family
K6-2
K6-3
AMD Athlon(TM) Processor Family
AMD2900 Family
K6-2+
Power PC Family
Power PC 601
Power PC 603
Power PC 603+
Power PC 604
Power PC 620
Power PC x704
Power PC 750
Unnasigned_28
Unnasigned_29
Unnasigned_2A
Unnasigned_2B
Unnasigned_2C
Unnasigned_2D
Unnasigned_2E
Unnasigned_2F
Alpha Family3
Alpha 21064
Alpha 21066
Alpha 21164
Alpha 21164PC
Alpha 21164a
Alpha 21264
Alpha 21364
Unnasigned_38
Unnasigned_39
Unnasigned_3A
Unnasigned_3B
Unnasigned_3C
Unnasigned_3D
Unnasigned_3E
Unnasigned_3F
MIPS Family
MIPS R4000
MIPS R4200
MIPS R4400
MIPS R4600
MIPS R10000
Unnasigned_46
Unnasigned_47
Unnasigned_48
Unnasigned_49
Unnasigned_4A
Unnasigned_4B
Unnasigned_4C
Unnasigned_4D
Unnasigned_4E
Unnasigned_4F
SPARC Family
SuperSPARC
microSPARC II
microSPARC IIep
UltraSPARC
UltraSPARC II
UltraSPARC IIi
UltraSPARC III
UltraSPARC IIIi
Unnasigned_59
Unnasigned_5A
Unnasigned_5B
Unnasigned_5C
Unnasigned_5D
Unnasigned_5E
Unnasigned_5F
68040 Family
68xxx
68000
68010
68020
68030
Unnasigned_66
Unnasigned_67
Unnasigned_68
Unnasigned_69
Unnasigned_6A
Unnasigned_6B
Unnasigned_6C
Unnasigned_6D
Unnasigned_6E
Unnasigned_6F
Hobbit Family
Unnasigned_71
Unnasigned_72
Unnasigned_73
Unnasigned_74
Unnasigned_75
Unnasigned_76
Unnasigned_77
Crusoe(TM) TM5000 Family
Crusoe(TM) TM3000 Family
Efficeon(TM) TM8000 Family
Unnasigned_7B
Unnasigned_7C
Unnasigned_7D
Unnasigned_7E
Unnasigned_7F
Weitek
Unnasigned_81
Itanium(TM) processor
AMD Athlon(TM) 64 Processor Family
AMD Opteron(TM) Processor Family
Unnasigned_85
Unnasigned_86
Unnasigned_87
Unnasigned_88
Unnasigned_89
Unnasigned_8A
Unnasigned_8B
Unnasigned_8C
Unnasigned_8D
Unnasigned_8E
Unnasigned_8F
PA-RISC Family
PA-RISC 8500
PA-RISC 8000
PA-RISC 7300LC
PA-RISC 7200
PA-RISC 7100LC
PA-RISC 7100
Unnasigned_97
Unnasigned_98
Unnasigned_99
Unnasigned_9A
Unnasigned_9B
Unnasigned_9C
Unnasigned_9D
Unnasigned_9E
Unnasigned_9F
V30 Family
Unnasigned_A1
Unnasigned_A2
Unnasigned_A3
Unnasigned_A4
Unnasigned_A5
Unnasigned_A6
Unnasigned_A7
Unnasigned_A8
Unnasigned_A9
Unnasigned_AA
Unnasigned_AB
Unnasigned_AC
Unnasigned_AD
Unnasigned_AE
Unnasigned_AF
Pentium(R) III Xeon(TM) processor
Pentium(R) III Processor with Intel(R) SpeedStep(TM) Technology
Pentium(R) 4 Processor
Intel(R) Xeon(TM)
AS400 Family
Intel(R) Xeon(TM) processor MP
AMD Athlon(TM) XP Processor Family
AMD Athlon(TM) MP Processor Family
Intel(R) Itanium(R) 2 processor
Intel(R) Pentium(R) M processor
Unnasigned_BA
Unnasigned_BB
Unnasigned_BC
Unnasigned_BD
Unnasigned_BE
Unnasigned_BF
Unnasigned_C0
Unnasigned_C1
Unnasigned_C2
Unnasigned_C3
Unnasigned_C4
Unnasigned_C5
Unnasigned_C6
Unnasigned_C7
IBM390 Family
G4
G5
Unnasigned_CB
Unnasigned_CC
Unnasigned_CD
Unnasigned_CE
Unnasigned_CF
Unnasigned_D0
Unnasigned_D1
Unnasigned_D2
Unnasigned_D3
Unnasigned_D4
Unnasigned_D5
Unnasigned_D6
Unnasigned_D7
Unnasigned_D8
Unnasigned_D9
Unnasigned_DA
Unnasigned_DB
Unnasigned_DC
Unnasigned_DD
Unnasigned_DE
Unnasigned_DF
Unnasigned_E0
Unnasigned_E1
Unnasigned_E2
Unnasigned_E3
Unnasigned_E4
Unnasigned_E5
Unnasigned_E6
Unnasigned_E7
Unnasigned_E8
Unnasigned_E9
Unnasigned_EA
Unnasigned_EB
Unnasigned_EC
Unnasigned_ED
Unnasigned_EE
Unnasigned_EF
Unnasigned_F0
Unnasigned_F1
Unnasigned_F2
Unnasigned_F3
Unnasigned_F4
Unnasigned_F5
Unnasigned_F6
Unnasigned_F7
Unnasigned_F8
Unnasigned_F9
i860
i960
Unnasigned_FC
Unnasigned_FD
Unnasigned_FE
Unnasigned_FF

)