//
// 00h Unassigned_00
// 01h Other
// 02h Unknown
// 03h 8086
// 04h 80286
// 05h Intel386™ processor
// 06h Intel486™ processor
// 07h 8087
// 08h 80287
// 09h 80387
// 0Ah 80487
// 0Bh Pentium® processor Family
// 0Ch Pentium® Pro processor
// 0Dh Pentium® II processor
// 0Eh Pentium® processor with MMX™ technology
// 0Fh Celeron™ processor
// 10h Pentium® II Xeon™ processor
// 11h Pentium® III processor
// 12h M1 Family
// 13h M2 Family
// 14h Unassigned_14
// 15h Unassigned_15
// 16h Unassigned_16
// 17h Unassigned_17
// 18h AMD Duron™ Processor Family
// 19h K5 Family
// 1Ah K6 Family
// 1Bh K6-2
// 1Ch K6-3
// 1Dh AMD Athlon™ Processor Family
// 1Eh AMD2900 Family
// 1Fh K6-2+
// 20h Power PC Family
// 21h Power PC 601
// 22h Power PC 603
// 23h Power PC 603+
// 24h Power PC 604
// 25h Power PC 620
// 26h Power PC x704
// 27h Power PC 750
// 28h Unassigned_28
// 29h Unassigned_29
// 2Ah Unassigned_2A
// 2Bh Unassigned_2B
// 2Ch Unassigned_2C
// 2Dh Unassigned_2D
// 2Eh Unassigned_2E
// 2Fh Unassigned_2F
// 30h Alpha Family3
// 31h Alpha 21064
// 32h Alpha 21066
// 33h Alpha 21164
// 34h Alpha 21164PC
// 35h Alpha 21164a
// 36h Alpha 21264
// 37h Alpha 21364
// 38h Unassigned_38
// 39h Unassigned_39
// 3Ah Unassigned_3A
// 3Bh Unassigned_3B
// 3Ch Unassigned_3C
// 3Dh Unassigned_3D
// 3Eh Unassigned_3E
// 3Fh Unassigned_3F
// 40h MIPS Family
// 41h MIPS R4000
// 42h MIPS R4200
// 43h MIPS R4400
// 44h MIPS R4600
// 45h MIPS R10000
// 46h Unassigned_46
// 47h Unassigned_47
// 48h Unassigned_48
// 49h Unassigned_49
// 4Ah Unassigned_4A
// 4Bh Unassigned_4B
// 4Ch Unassigned_4C
// 4Dh Unassigned_4D
// 4Eh Unassigned_4E
// 4Fh Unassigned_4F
// 50h SPARC Family
// 51h SuperSPARC
// 52h microSPARC II
// 53h microSPARC IIep
// 54h UltraSPARC
// 55h UltraSPARC II
// 56h UltraSPARC IIi
// 57h UltraSPARC III
// 58h UltraSPARC IIIi
// 59h Unassigned_59
// 5Ah Unassigned_5A
// 5Bh Unassigned_5B
// 5Ch Unassigned_5C
// 5Dh Unassigned_5D
// 5Eh Unassigned_5E
// 5Fh Unassigned_5F
// 60h 68040 Family
// 61h 68xxx
// 62h 68000
// 63h 68010
// 64h 68020
// 65h 68030
// 66h Unassigned_66
// 67h Unassigned_67
// 68h Unassigned_68
// 69h Unassigned_69
// 6Ah Unassigned_6A
// 6Bh Unassigned_6B
// 6Ch Unassigned_6C
// 6Dh Unassigned_6D
// 6Eh Unassigned_6E
// 6Fh Unassigned_6F
// 70h Hobbit Family
// 71h Unassigned_71
// 72h Unassigned_72
// 73h Unassigned_73
// 74h Unassigned_74
// 75h Unassigned_75
// 76h Unassigned_76
// 77h Unassigned_77
// 78h Crusoe™ TM5000 Family
// 79h Crusoe™ TM3000 Family
// 7Ah Efficeon™ TM8000 Family
// 7Bh Unassigned_7B
// 7Ch Unassigned_7C
// 7Dh Unassigned_7D
// 7Eh Unassigned_7E
// 7Fh Unassigned_7F
// 80h Weitek
// 81h Unassigned_81
// 82h Itanium™ processor
// 83h AMD Athlon™ 64 Processor Family
// 84h AMD Opteron™ Processor Family
// 85h Unassigned_85
// 86h Unassigned_86
// 87h Unassigned_87
// 88h Unassigned_88
// 89h Unassigned_89
// 8Ah Unassigned_8A
// 8Bh Unassigned_8B
// 8Ch Unassigned_8C
// 8Dh Unassigned_8D
// 8Eh Unassigned_8E
// 8Fh Unassigned_8F
// 90h PA-RISC Family
// 91h PA-RISC 8500
// 92h PA-RISC 8000
// 93h PA-RISC 7300LC
// 94h PA-RISC 7200
// 95h PA-RISC 7100LC
// 96h PA-RISC 7100
// 97h Unassigned_97
// 98h Unassigned_98
// 99h Unassigned_99
// 9Ah Unassigned_9A
// 9Bh Unassigned_9B
// 9Ch Unassigned_9C
// 9Dh Unassigned_9D
// 9Eh Unassigned_9E
// 9Fh Unassigned_9F
// A0h V30 Family
// A1h Unassigned_A1
// A2h Unassigned_A2
// A3h Unassigned_A3
// A4h Unassigned_A4
// A5h Unassigned_A5
// A6h Unassigned_A6
// A7h Unassigned_A7
// A8h Unassigned_A8
// A9h Unassigned_A9
// AAh Unassigned_AA
// ABh Unassigned_AB
// ACh Unassigned_AC
// ADh Unassigned_AD
// AEh Unassigned_AE
// AFh Unassigned_AF
// B0h Pentium® III Xeon™ processor
// B1h Pentium® III Processor with Intel® SpeedStep™ Technology
// B2h Pentium® 4 Processor
// B3h Intel® Xeon™
// B4h AS400 Family
// B5h Intel® Xeon™ processor MP
// B6h AMD Athlon™ XP Processor Family
// B7h AMD Athlon™ MP Processor Family
// B8h Intel® Itanium® 2 processor
// B9h Intel® Pentium® M processor
// BAh Unassigned_BA
// BBh Unassigned_BB
// BCh Unassigned_BC
// BDh Unassigned_BD
// BEh Unassigned_BE
// BFh Unassigned_BF
// C0h Unassigned_C0
// C1h Unassigned_C1
// C2h Unassigned_C2
// C3h Unassigned_C3
// C4h Unassigned_C4
// C5h Unassigned_C5
// C6h Unassigned_C6
// C7h Unassigned_C7
// C8h IBM390 Family
// C9h G4
// CAh G5
// CBh Unassigned_CB
// CCh Unassigned_CC
// CDh Unassigned_CD
// CEh Unassigned_CE
// CFh Unassigned_CF
// D0h Unassigned_D0
// D1h Unassigned_D1
// D2h Unassigned_D2
// D3h Unassigned_D3
// D4h Unassigned_D4
// D5h Unassigned_D5
// D6h Unassigned_D6
// D7h Unassigned_D7
// D8h Unassigned_D8
// D9h Unassigned_D9
// DAh Unassigned_DA
// DBh Unassigned_DB
// DCh Unassigned_DC
// DDh Unassigned_DD
// DEh Unassigned_DE
// DFh Unassigned_DF
// E0h Unassigned_E0
// E1h Unassigned_E1
// E2h Unassigned_E2
// E3h Unassigned_E3
// E4h Unassigned_E4
// E5h Unassigned_E5
// E6h Unassigned_E6
// E7h Unassigned_E7
// E8h Unassigned_E8
// E9h Unassigned_E9
// EAh Unassigned_EA
// EBh Unassigned_EB
// ECh Unassigned_EC
// EDh Unassigned_ED
// EEh Unassigned_EE
// EFh Unassigned_EF
// F0h Unassigned_F0
// F1h Unassigned_F1
// F2h Unassigned_F2
// F3h Unassigned_F3
// F4h Unassigned_F4
// F5h Unassigned_F5
// F6h Unassigned_F6
// F7h Unassigned_F7
// F8h Unassigned_F8
// F9h Unassigned_F9
// FAh i860
// FBh i960
// FCh Unassigned_FC
// FDh Unassigned_FD
// FEh Unassigned_FE
// FFh Unassigned_FF
//

